import { Inter } from "next/font/google";
import "./globals.css";
import local from 'next/font/local';

const inter = Inter({ subsets: ["latin"] });

const nimbus = local({
  src: [
    {
      path: './TAN-NIMBUS.ttf',
      weight: '800',
    },
  ],
  variable: '--font-nimbus',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nimbus.variable} ${inter.className}`}>{children}</body>
    </html>
  );
}
